# -*- coding: utf-8 -*-
"""Movie data analysis of netflix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QKkli_stl104703ZQu9VGso9HoMLERQB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

ds = pd.read_csv('/content/mymoviedb.csv',lineterminator="\n")

ds.head(1)

ds.info()

ds["Genre"].head()

ds.duplicated().sum()

ds['Popularity'].max()

ds['Popularity'].min()

"""Describe give us a functionlity  to give mathemethical infomation of operations"""

ds.describe()

"""Change datatype of Release Date"""

ds['Release_Date'] = pd.to_datetime(ds['Release_Date'])

"""Check Data type will be change or not"""

print(ds['Release_Date'].dtype)

"""Remove month or day from the Release Date"""

ds['Release_Date'] =ds['Release_Date'].dt.year
ds['Release_Date'].dtype

"""show frist 5 data"""

ds.head()

"""Extra column remove which are not usefull for us.
col - ['Overview','Original_Language','Poster_Url']
"""

cols =['Overview','Original_Language','Poster_Url']

ds.drop(cols, axis=1, inplace =True)

"""show column"""

ds.columns

ds.head()

"""we would cut the vote average value and make 4 categries: popular , average, below_avg,not_popular catigorize_col function provided above"""

def catigorize_col(ds,col,labels):


  edges = [ds[col].describe()['min'],
           ds[col].describe()['25%'],
           ds[col].describe()['50%'],
           ds[col].describe()['75%'],
           ds[col].describe()['max']]


  ds[col] = pd.cut(ds[col], edges, labels = labels, duplicates = 'drop')
  return ds

labels = ['not_popular','below_avg','average','popular']


catigorize_col(ds,'Vote_Average',labels)


ds['Vote_Average'].unique()

ds.head(10)

"""check populer movies"""

ds['Vote_Average'].value_counts()

ds.dropna(inplace= True)

ds.isna().sum()

ds.head()

ds['Genre'] =ds['Genre'].str.split(', ')
ds = ds.explode('Genre').reset_index(drop = True)
ds.head()

"""Casting column into cateogy"""

# Casting column into cateogy

ds['Genre'] =ds['Genre'].astype('category')
ds['Genre'].dtypes

ds.info()

ds.nunique()

ds.head()

Data visualization

#data visualization

sns.set_style('whitegrid')

ds['Genre'].describe()

sns.catplot(y='Genre', data= ds , kind = 'count', order=ds['Genre'].value_counts().index,
            color = '#4287f5')
plt.title("Genre colum distribution")
plt.show()

"""Which is the hightest vote avg in vote avg"""

#Which is the hightest vote avg in vote avg
ds.head()